from app.core.controllers.activity import *
from app.core.controllers.consult import *
from app.core.controllers.event import *
from app.core.controllers.form import *
from app.core.controllers.form_meta import *
from app.core.controllers.lesson import *
from app.core.controllers.lesson_record import *
from app.core.controllers.model_lesson import *
from app.core.controllers.notice_lesson import *
from app.core.controllers.user import *
