from app.core.controller.activity import *
from app.core.controller.consult import *
from app.core.controller.event import *
from app.core.controller.form import *
from app.core.controller.form_meta import *
from app.core.controller.lesson import *
from app.core.controller.lesson_record import *
from app.core.controller.model_lesson import *
from app.core.controller.notice_lesson import *
from app.core.controller.user import *
from app.core.controller.notices import *
from app.core.controller.page_data import *
from app.core.controller.captcha import *
from app.core.controller.other_model_lesson import *
