from app.core.controller.activity import *
from app.core.controller.consult import *
from app.core.controller.event import *
from app.core.controller.form import *
from app.core.controller.form_meta import *
from app.core.controller.lesson import *
from app.core.controller.lesson_record import *
from app.core.controller.model_lesson import *
from app.core.controller.notice_lesson import *
from app.core.controller.user import *
